assist_rdv/assist_rdv/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls'))
    
]

assist_rdv/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . views import logoutUser
from django.contrib.auth import logout
from .views import make_appointment


app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/',views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('make/', make_appointment, name='make'),
]

assist_rdv/item/urls.py
from django.urls import path

from . import views


app_name = 'item'

urlpatterns = [
    path('new/', views.new,name='new'),
    path('<int:pk>', views.detail,name='detail'),
    path('<int:pk>/delete/', views.delete,name='delete'),
    path('<int:pk>/edit/', views.edit,name='edit'),
    path('', views.browse,name='browse'),

]

assist_rdv/item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True,null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name = 'items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

# Create your models here.

assist_rdv/item/forms.py
from django import forms
from .models import Item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description','price','image',)
        
        widgets = {
            'category':forms.Select,
            'name':forms.TextInput,
            'description':forms.Textarea,
            'price':forms.TextInput,
            'image':forms.FileInput,
            
        }
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','description','price','image','is_sold',)
        
        widgets = {
            'name':forms.TextInput,
            'description':forms.Textarea,
            'price':forms.TextInput,
            'image':forms.FileInput,
            
        }

assist_rdv/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Item, Category
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm


def browse(request):
    query = request.GET.get('query','')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)
    
    if category_id:
        items = items.filter(category_id=category_id)
    
    if query:
        items =items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'item/browse.html',{
        'items':items,
        'query':query,
        'category':categories,
        'category': int(category_id),
    })



def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html',{
        'item':item,
        'related_items': related_items
    })
    
@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit = False)
            item.created_by = request.user
            item.save()
            
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()
    
    return render(request,'item/form.html',{
        'form':form,
        'title':'New Item'
    })

def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()
            
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)
    
    return render(request,'item/form.html',{
        'form':form,
        'title':'Edit Item'
    })



@login_required
def delete(request,pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')
# Create your views here.

assist_rdv/item/templates/item/browse.html
{% extends 'core/base.html' %}


{% block title %}Browse{% endblock title %}


{% block content %}

<div class=BrowseContent>
    <div>
        Side Bar
        <form method = "get" action="{% url 'item:browse' %}">
            <input name="query" class=ListSearch type="text" value="{{query}}" placeholder="Find a bike, a chair ou a car.">

            <button class=SearchButton>Search</button>
        </form>

        <p class= TitleCategories>Categories</p>
        <ul class= ListCategories>
            
            {% for category in categories %}
                <li> 
                    <a href="{% url 'item:browse' %}?query={{query}}&category={{category.id}}">{{category.name}}</a>
                    
                </li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <div class=GridItemsBrowse>
            {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">Click</a>
                <div>
                    <img src="{{item.image.url}}" alt="">
                </div>
                <div>
                    <h2>{{item.name}}</h2>
                    <p>Price : {{item.price}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

assist_rdv/item/templates/item/detail.html
{% extends 'core/base.html' %}



{% block title %}{{item.name}}{% endblock title %}


{% block content %}
<div class=GridDetail>
    <div class=DetailImage>
        <img src="{{item.image.url}}" alt="">
    </div>
    <div class=NameArticle>
        <h1> {{item.name}}</h1>
        <p class=PriceArticle>Price :{{item.price}}</p>
        <p class=SellerArticle>Seller:{{item.created_by.username}}</p>
        {% if item.description %}
        <p class=DescArticle>Description<br>  
            {{item.description}}
        </p>
        {% endif %}
        {% if request.user == item.created_by%}
        <div>
            <p>This is your item!</p>
            <a href="{% url 'item:edit' item.id %}">Edit</a><br>
            <br>
            <a href="{% url 'item:delete' item.id %}">Delete Item</a>
        </div>
        {% else %}
        <a href="#">Contact Seller</a>
        {% endif %}
    </div>
</div>
<div class=NewItemsDisplay>
    <h2 class=TitleNewItems>Related Items</h2>
    <div class=GridItems>
        {% for item in related_items %}
        <div>
            <a href="{% url 'item:detail' item.id %}">Click</a>
            <div>
                <img src="{{item.image.url}}" alt="">
            </div>
            <div>
                <h2>{{item.name}}</h2>
                <p>Price : {{item.price}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

assist_rdv/item/templates/item/form.html
{% extends 'core/base.html' %}


{% block title %}{{title}}{% endblock title %}

{% block content %}
<h1 class=NewItemContentTitle>{{title}}</h1>
<form method='post'action="." enctype="multipart/form-data">
{% csrf_token %}

<div class=NewItemContentStuff>
    {{form.as_p}}
</div>
{% if form.errors or form.non_field_errors %}
    <div>
        {% for field in form %}
            {{field.errors}}
            {{form.non_field_errors}}
        {% endfor %}
    </div>

    
    {% endif %}

    <button class=ButtonSubmit> Submit</button>

</form>
{% endblock content %}