assist_rdv/assist_rdv/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls'))
    
]

assist_rdv/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . views import logoutUser
from django.contrib.auth import logout
from .views import make_appointment


app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/',views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('make/', make_appointment, name='make'),
]

assist_rdv/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index,name='index'),
    
]

assist_rdv/item/urls.py
from django.urls import path

from . import views


app_name = 'item'

urlpatterns = [
    path('new/', views.new,name='new'),
    path('<int:pk>', views.detail,name='detail'),
    path('<int:pk>/delete/', views.delete,name='delete'),
    path('<int:pk>/edit/', views.edit,name='edit'),
    path('', views.browse,name='browse'),

]

assist_rdv/core/models.py
from django.db import models



class Appointment(models.Model):
    date = models.DateField()
    time = models.TimeField()
    client_name = models.CharField(max_length=200)
    client_phone = models.CharField(max_length=15)
    client_email = models.EmailField()
    client_note = models.TextField(max_length=900)
    



# Create your models here.

assist_rdv/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from .models import Appointment

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('date', 'time', 'client_name', 'client_phone', 'client_email','client_note')
        





class LoginForm(AuthenticationForm):
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',

    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',

    }))

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',

    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email adress',

    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',

    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',

    }))

assist_rdv/core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item
from django.contrib.auth import logout
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required
from .forms import AppointmentForm

@login_required
def make_appointment(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('appointments')
    else:
        form = AppointmentForm()
    return render(request, 'make_appointment.html', {'form': form})


def logoutUser(request):
    logout(request)
    
    return redirect('/login')    




# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold = False)[0:6]
    categories = Category.objects.all()
    
    return render(request, 'core/index.html',{
        'categories':categories,
        'items':items,
    })

def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else:
        form = SignUpForm()
    
    return render(request,'core/signup.html',{
        'form':form
    })

assist_rdv/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>src="https://cdn.tailwindcss.com"</script>
    
    <title>{% block title %}  {% endblock title %} | Title</title>
</head>
    <body>
        <nav class = Navigation>
            <a href="/" class= Logo>Puddle</a>
            <ul class = ItemsNav>
                <li><a href="{% url 'core:contact' %}">Contact</a></li>
                <li><form method="post">
                    {% csrf_token %}
                    <div>
                      <label for="appoint_date">Date de rendez-vous :</label>
                      <input type="text" id="appoint_date" name="appoint_date" />
                    </div>
                    <div>
                      <label for="appoint_time">Heure de rendez-vous :</label>
                      <input type="text" id="appoint_time" name="appoint_time" />
                    </div>
                    <div>
                      <label for="appoint_reason">Raison de rendez-vous :</label>
                      <textarea id="appoint_reason" name="appoint_reason"></textarea>
                    </div>
                    <input type="submit" value="Prendre rendez-vous">
                  </form>
                  
                </li>
                <li><a href="{% url 'item:new' %}">New Item</a></li>
                <li><a href="{% url 'item:browse' %}">Browse</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'core:logout' %}">Logout</a></li>
                <li><a href="#">Inbox</a></li>
                <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
                {% else %}
                <li><a href="{% url 'core:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'core:login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </nav>
        <div class = BaseContent>
        {% block content %}

        {% endblock content %}
        </div>
        <footer class=Footer>
            <div class=FooterInfo>
                <h3 class=FooterInfoTitle>About</h3>
                <p class=FooterText>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa molestias nostrum rem, ex eius eos? Recusandae quibusdam quidem, dolorum atque quis in ipsum excepturi dolore velit quam a vero molestias.</p>
                <ul class=FooterMenuItems>
                    <li><a href="#"></a>Contact</li>
                    <li><a href="#"></a>A Propos</li>
                    <li><a href="#"></a>Sign Up</li>
                </ul>
        </footer>
    </body>
</html>

assist_rdv/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}
Contact
{% endblock title %}



{% block content %}
<h1> The contact page </h1>



{% endblock content %}

assist_rdv/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
Welcome
{% endblock title %}



{% block content %}
<div class=NewItemsDisplay>
    <h2 class=TitleNewItems>New Items</h2>
    <div class=GridItems>
        {% for item in items %}
        <div>
            <a href="{% url 'item:detail' item.id %}">Click</a>
            <div>
                <img src="{{item.image.url}}" alt="">
            </div>
            <div>
                <h2>{{item.name}}</h2>
                <p>Price : {{item.price}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class=NewItemsDisplay>
    <h2 class=TitleNewItems>Categories</h2>
    <div class=GridItems>
        {% for category in categories %}
            <div>
                <a href="#"></a>
 
                <div>
                    <h2>{{category.name}}</h2>
                    <p> {{category.items.count}} Items</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>



{% endblock content %}

assist_rdv/core/templates/core/login.html
{% extends 'core/base.html' %}


{% block title %}Sign up{% endblock title %}

{% block content %}
<div class=SignWindow>
    <h1 class=TitleSignUp> Login</h1>
    <form method='post' action=".">
        {%csrf_token%}
    

        <div>
            <label class=Label>
                Username
            </label><br>
            {{form.username}}
        </div>
        <div>
            <label class=Label>
                Password
            </label><br>
            {{form.password}}
        </div>
        

        {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form %}
                {{field.errors}}
                {{form.non_field_errors}}
            {% endfor %}
        </div>

        
        {% endif %}
        <button class=ButtonSubmit> Submit</button>
    </form>
</div>

{% endblock content %}

assist_rdv/core/templates/core/signup.html
{% extends 'core/base.html' %}


{% block title %}Sign up{% endblock title %}

{% block content %}
<div class=SignWindow>
    <h1 class=TitleSignUp> Sign up</h1>
    <form method='post' action=".">
        {%csrf_token%}
    

        <div>
            <label class=Label>
                Username
            </label><br>
            {{form.username}}
        </div>
        <div>
            <label class=Label>
                Email
            </label><br>
            {{form.email}}
        </div>
        <div>
            <label class=Label>
                Password
            </label><br>
            {{form.password1}}
        </div>
        <div>
            <label class=Label>
                Repeat Password
            </label><br>
            {{form.password2}}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form %}
                {{field.errors}}
                {{form.non_field_errors}}
            {% endfor %}
        </div>

        
        {% endif %}
        <button class=ButtonSubmit> Submit</button>
    </form>
</div>

{% endblock content %}